<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>smt</string>
	</array>
	<key>name</key>
	<string>uSmalltalk</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>SET</string>
			<key>match</key>
			<string>\b(?:set)\s+</string>
			<key>name</key>
			<string>variable.parameter.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>BEGIN</string>
			<key>match</key>
			<string>\b(?:begin)\s+</string>
			<key>name</key>
			<string>variable.parameter.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>BLOCK</string>
			<key>match</key>
			<string>\b(?:block)\s+</string>
			<key>name</key>
			<string>variable.parameter.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LITERAL</string>
			<key>match</key>
			<string>()#((\w|\d|-)*)\b</string>
			<key>name</key>
			<string>string.unquoted.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>VAL</string>
			<key>match</key>
			<string>\b(?:val)\s+</string>
			<key>name</key>
			<string>keyword.other.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>DEFINE</string>
			<key>match</key>
			<string>\b(?:define)\s+</string>
			<key>name</key>
			<string>support.class.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CLASS</string>
			<key>match</key>
			<string>\b(?:class)\s+</string>
			<key>name</key>
			<string>support.class.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>USE</string>
			<key>match</key>
			<string>\b(?:use)\s+</string>
			<key>name</key>
			<string>variable.parameter.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CHECK-EXPECT</string>
			<key>match</key>
			<string>\b(?:check-expect)\s+</string>
			<key>name</key>
			<string>support.function.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CHECK-ERROR</string>
			<key>match</key>
			<string>\b(?:check-error)\s+</string>
			<key>name</key>
			<string>support.function.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>METHOD</string>
			<key>match</key>
			<string>\b(?:method)\s+</string>
			<key>name</key>
			<string>support.class.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>CLASS-METHOD</string>
			<key>match</key>
			<string>\b(?:class-method)\s+</string>
			<key>name</key>
			<string>support.class.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>LOCALS</string>
			<key>match</key>
			<string>\b(?:locals)\s+</string>
			<key>name</key>
			<string>entity.name.function.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>COMMENT</string>
			<key>match</key>
			<string>(;[^\n]*)</string>
			<key>name</key>
			<string>comment.line.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<true/>
			<key>match</key>
			<string>\b(?:true)\s+</string>
			<key>name</key>
			<string>constant.language.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<false/>
			<key>match</key>
			<string>\b(?:false)\s+</string>
			<key>name</key>
			<string>constant.language.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>NIL</string>
			<key>match</key>
			<string>\b(?:nil)\s+</string>
			<key>name</key>
			<string>constant.language.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>IF</string>
			<key>match</key>
			<string>\b(?:if)\s+</string>
			<key>name</key>
			<string>variable.parameter.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>WHILE</string>
			<key>match</key>
			<string>\b(?:while)\s+</string>
			<key>name</key>
			<string>variable.parameter.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>NEW</string>
			<key>match</key>
			<string>\b(?:new)\s+</string>
			<key>name</key>
			<string>storage.modifier.smt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>FUNCTION</string>
			<key>match</key>
			<string>\b[\w]+:()</string>
			<key>name</key>
			<string>keyword.smt</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.smt</string>
	<key>uuid</key>
	<string>08263e94-390d-417d-b02a-eb554d32f8f6</string>
</dict>
</plist>
